apiVersion: v1
kind: Namespace
metadata:
  name: markov
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: markov-init
  namespace: markov
data:
  markov-init.cql: |
    CREATE KEYSPACE IF NOT EXISTS markov WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
    USE MARKOV;
    CREATE TABLE IF NOT EXISTS markov_names (markov_name TEXT, markov_id UUID, PRIMARY KEY (markov_name));
    CREATE TABLE IF NOT EXISTS markov_data (markov_id UUID, seed BLOB, value BLOB, count COUNTER, PRIMARY KEY (markov_id, seed, value));
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: markov
spec:
  template:
    spec:
      containers:
      - name: db-init
        image: nuvo/docker-cqlsh
        env:
        - name: CQLSH_HOST
          value: cassandra.cassandra
        volumeMounts:
        - name: init-scripts
          mountPath: /scripts
      restartPolicy: Never
      volumes:
      - name: init-scripts
        configMap:
          name: markov-init
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markov-crud
  namespace: markov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markov-crud
  template:
    metadata:
      labels:
        app: markov-crud
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: markov
        image: nexus.lan:5000/markov-crud
        imagePullPolicy: Always
        env:
        - name: CASSANDRA_HOST
          value: cassandra.cassandra
        ports:
        - name: http
          containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: markov-sentence-generator
  namespace: markov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: markov-sentence-generator
  template:
    metadata:
      labels:
        app: markov-sentence-generator
    spec:
      nodeSelector:
        beta.kubernetes.io/arch: amd64
      containers:
      - name: markov
        image: nexus.lan:5000/markov-sentence-generator
        imagePullPolicy: Always
        env:
        - name: CASSANDRA_HOST
          value: cassandra.cassandra
        ports:
        - name: http
          containerPort: 5000
---
kind: Service
apiVersion: v1
metadata:
  name: markov-crud
  namespace: markov
spec:
  type: ClusterIP
  selector:
    app: markov-crud
  clusterIP: None
  ports:
  - port: 80
    targetPort: http
---
kind: Service
apiVersion: v1
metadata:
  name: markov-sentence-generator
  namespace: markov
spec:
  type: ClusterIP
  selector:
    app: markov-sentence-generator
  clusterIP: None
  ports:
  - port: 80
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: markov
  namespace: markov
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    kubernetes.io/ingress.class: "internal"
spec:
  rules:
  - host: markov.lan
    http:
      paths:
      - path: /markovMaps
        backend:
          serviceName: markov-crud
          servicePort: 80
      - path: /markovMaps/.*/message
        backend:
          serviceName: markov-sentence-generator
          servicePort: 80