apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-react-app
  namespace: markov
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-react-app
  template:
    metadata:
      labels:
        app: simple-react-app
    spec:
      containers:
      - name: app
        image: docker.lan:5000/simple-react-app:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: simple-react-app
  namespace: markov
spec:
  type: ClusterIP
  selector:
    app: simple-react-app
  clusterIP: None
  ports:
  - port: 80
    targetPort: http
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: simple-react-app
  namespace: markov
  annotations:
    kubernetes.io/ingress.class: "internal"
spec:
  rules:
  - host: markov-app.lan
    http:
      paths:
      - backend:
          serviceName: simple-react-app
          servicePort: 80