name:                markov-services
version:             0.1.0.0
github:              "jali-clarke/markov"
license:             BSD3
author:              "Jinnah Ali-Clarke"
maintainer:          "jinnah.ali-clarke@outlook.com"
copyright:           "2019 Jinnah Ali-Clarke"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jali-clarke/markov#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring == 0.10.8.2
- containers == 0.6.0.1
- cql == 4.0.1
- cql-io == 1.1.1
- exceptions == 0.10.0
- MonadRandom == 0.5.1.1
- mtl == 2.2.2
- servant-server == 0.15
- text == 1.2.3.1
- warp == 3.2.26
- wai-extra == 3.0.25
- uuid == 1.3.13

library:
  source-dirs:
  - src/database
  - src/service-helpers
  ghc-options:
  - -Wall
  - -Werror

executables:
  markov-crud:
    main:                Main.hs
    source-dirs:         app/markov-crud
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - markov-api
    - markov-services

  markov-sentence-generator:
    main:                Main.hs
    source-dirs:         app/markov-sentence-generator
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - markov-api
    - markov-services